/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Models.*;
import Utils.Tools;
import Utils.XFile;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author thnrg
 */
public final class QuanLyMonAn extends javax.swing.JFrame {
    protected ArrayList<Dish> dishes = new ArrayList<>();
    /**
     * Creates new form QuanLyMonAn
     */
    public QuanLyMonAn() {
        initComponents();
        onRun();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDishID = new javax.swing.JTextField();
        txtDishName = new javax.swing.JTextField();
        txtDishPrice = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnListAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDish = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ MÓN ĂN");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Mã món ăn");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Tên món ăn");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Giá");

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnListAll.setText("List All");
        btnListAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllActionPerformed(evt);
            }
        });

        tblDish.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"TS00553", "Nguyễn Quóc Minh", "10000000"}
            },
            new String [] {
                "Mã món ăn", "Tên món ăn", "Giá"
            }
        ));
        jScrollPane1.setViewportView(tblDish);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDishName, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDishID))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDishPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(btnListAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDishID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDishName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDishPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        clearFields();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(readForm() != null)
        {
            dishes.add(readForm());
            loadToTable();
            saveToFile();
            clearFields();
            JOptionPane.showMessageDialog(this, "Thêm và lưu thành công!");
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnListAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllActionPerformed
        readFromFile();
        loadToTable();
    }//GEN-LAST:event_btnListAllActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(tblDish.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(this, "Chưa chọn hàng trong bảng!", "Warning", JOptionPane.WARNING_MESSAGE);
            tblDish.requestFocus();
        }
        else
        {
            for(Dish dish: dishes)
            {
                if(dish.getDishID().equals(tblDish.getValueAt(tblDish.getSelectedRow(), 0)))
                {
                    if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa món ăn " + dish.getDishName() + " Không?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION)
                    {
                        dishes.remove(dish);
                        saveToFile();
                        loadToTable();
                        JOptionPane.showMessageDialog(this, "Xóa thành công", "Information", JOptionPane.INFORMATION_MESSAGE);
                        break;
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Hành động xóa đã bị hủy", "Information", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    public final void onRun()
    {
        readFromFile();
        loadToTable();
    }
    
    public void clearFields()
    {
        txtDishID.setText("");
        txtDishName.setText("");
        txtDishPrice.setText("");
    }
    
    public Dish readForm()
    {
        if(txtDishID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Không được để trống mã món ăn!", "Warning", JOptionPane.WARNING_MESSAGE);
            txtDishID.requestFocus();
            return null;
        }
        if(txtDishName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Không được để trống tên món ăn!", "Warning", JOptionPane.WARNING_MESSAGE);
            txtDishName.requestFocus();
            return null;
        }
        if(txtDishPrice.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Không được để trống giá!", "Warning", JOptionPane.WARNING_MESSAGE);
            txtDishPrice.requestFocus();
            return null;
        }
        if(!Tools.isDouble(txtDishPrice.getText()))
        {
            JOptionPane.showMessageDialog(this, "Giá phải là số thực!", "Warning", JOptionPane.WARNING_MESSAGE);
            txtDishPrice.requestFocus();
            return null;
        }
        if(Double.parseDouble(txtDishPrice.getText()) < 0)
        {
            JOptionPane.showMessageDialog(this, "Giá phải là số dương!", "Warning", JOptionPane.WARNING_MESSAGE);
            txtDishPrice.requestFocus();
            return null;
        }
        for(Dish dish: dishes)
        {
            if(dish.getDishID().equalsIgnoreCase(txtDishID.getText()))
            {
                JOptionPane.showMessageDialog(this, "Trùng mã món ăn", "Warning", JOptionPane.WARNING_MESSAGE);
                txtDishName.requestFocus();
                return null;
            }
        }
        return new Dish(txtDishID.getText(), txtDishName.getText(), Double.parseDouble(txtDishPrice.getText()));
    }
    
    public void saveToFile()
    {
        XFile.writeObject("src/Files/DishList.dat", dishes);
    }
    
    public void readFromFile()
    {
        dishes = (ArrayList<Dish>) XFile.readObject("src/Files/DishList.dat");
        if(dishes == null)
        {
            dishes = new ArrayList<>();
        }
    }
    
    public void loadToTable()
    {
        if(dishes != null)
        {
            DefaultTableModel tbl1 = (DefaultTableModel) tblDish.getModel();
            tbl1.setRowCount(0);

            for(Dish dish: dishes)
            {
                tbl1.addRow(new Object[] {dish.getDishID(), dish.getDishName(), dish.getDishPrice()});
            }
            tblDish.setModel(tbl1);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyMonAn().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnListAll;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDish;
    private javax.swing.JTextField txtDishID;
    private javax.swing.JTextField txtDishName;
    private javax.swing.JTextField txtDishPrice;
    // End of variables declaration//GEN-END:variables
}
